CREATE TABLE `products` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`bling_product_id` text DEFAULT '' NOT NULL,
	`sku` text DEFAULT '' NOT NULL,
	`gtin` text DEFAULT '' NOT NULL,
	`name` text DEFAULT '' NOT NULL,
	`brand` text DEFAULT '' NOT NULL,
	`category` text DEFAULT '' NOT NULL,
	`subcategory` text DEFAULT '' NOT NULL,
	`supplier` text DEFAULT '' NOT NULL,
	`cost` real DEFAULT 0 NOT NULL,
	`sale_price` real DEFAULT 0 NOT NULL,
	`weight` real DEFAULT 0 NOT NULL,
	`width` real DEFAULT 0 NOT NULL,
	`height` real DEFAULT 0 NOT NULL,
	`length` real DEFAULT 0 NOT NULL,
	`stock_physical` real DEFAULT 0 NOT NULL,
	`stock_reserved` real DEFAULT 0 NOT NULL,
	`min_stock` real DEFAULT 0 NOT NULL,
	`max_stock` real DEFAULT 0 NOT NULL,
	`location` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'ativo' NOT NULL,
	`last_sale_at` text DEFAULT '' NOT NULL,
	`synced_at` text DEFAULT '' NOT NULL,
	`updated_by` text DEFAULT '' NOT NULL
);
