"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type Item={id:number;sku:string;product_name:string;platform:string;status:string;sale_price:number;ml_price:number;shopee_price:number;cost:number;packaging_cost:number;extra_cost:number;ml_modality:string;title:string;description:string;ml_title:string;shopee_title:string;ml_description:string;shopee_description:string;packaging:string;weight:number;width:number;length:number;height:number;image_keys:string[];listing_url:string;gtin:string;brand:string;model:string;package_volume:string;units_per_pack:number;stock_quantity:number;ml_catalog_product_id:string;ml_category_id:string;ml_item_id:string;ml_permalink:string;ml_publish_status:string;ml_error:string};
type ImportRow={row:number;sku:string;productName:string;salePrice:string;weight:string;width:string;length:string;height:string;valid:boolean};
type PriceConfig={margem:number;imposto:number;tacos:number;divisor_cubico:number;ml_comissao_classico:number;ml_comissao_premium:number;shopee_faixas:{min:number;max:number;comissao:number;fixa:number}[];ml_frete:{min:number;max:number;frete:number[][]}[]};
type MlConnection={configured:boolean;connected:boolean;clientId:string;mlUserId:string;tokenExpiresAt:string;callbackUrl:string;notificationUrl:string;lastError:string};
type ShopeeConnection={environment:"sandbox"|"production";configured:boolean;connected:boolean;partnerId:string;shopId:string;tokenExpiresAt:string;callbackUrl:string;lastError:string};
type BlingConnection={configured:boolean;connected:boolean;clientId:string;companyId:string;callbackUrl:string;webhookUrl:string;lastError:string};
type BlingProduct={id:string;name:string;sku:string;gtin:string;salePrice:number;cost:number;stock:number;weight:number;width:number;length:number;height:number;brand:string;picture:string;status:string;format:string};
type CatalogCandidate={id:string;name:string;status:string;domainId:string;categoryId:string;picture:string;brand:string;model:string;gtin:string;packageVolume:string};
type CategorySuggestion={id:string;name:string;path:string;domainId:string;requiredAttributes:{id:string;name:string}[]};
type ShopeeCategory={id:number;name:string;parentId:number;hasChildren:boolean};
type ShopeeLogistic={id:number;name:string};
const empty={sku:"",productName:"",platform:"ambos",status:"preparacao",salePrice:"",mlPrice:"",shopeePrice:"",cost:"",packagingCost:"",extraCost:"",mlModality:"classico",title:"",description:"",mlTitle:"",shopeeTitle:"",mlDescription:"",shopeeDescription:"",packaging:"",weight:"",width:"",length:"",height:"",imageKeys:[] as string[],listingUrl:"",gtin:"",brand:"",model:"",packageVolume:"",unitsPerPack:1,stockQuantity:1,mlCatalogProductId:"",mlCategoryId:"",mlItemId:"",mlPermalink:"",mlPublishStatus:"",mlError:"",shopeeCategoryId:"",shopeeLogisticId:"",shopeeItemId:"",shopeeError:""};
const statuses:Record<string,string>={preparacao:"Em preparação",pronto:"Pronto para publicar",publicado:"Publicado"};
const platforms:Record<string,string>={shopee:"Shopee",mercado_livre:"Mercado Livre",ambos:"Shopee + Mercado Livre"};
const packages:Record<string,{label:string;cost:number;width:number;length:number;height:number}>={
 cx01:{label:"Cx 01 — 18 × 18 × 31 cm",cost:1.5,width:18,length:18,height:31},
 cx02:{label:"Cx 02 — 14 × 27 × 9 cm",cost:1.5,width:14,length:27,height:9},
 cx03:{label:"Cx 03 — 10 × 19 × 9 cm",cost:1.5,width:10,length:19,height:9},
 saco2030:{label:"Saco 20 × 30 × 5 cm",cost:.1,width:20,length:30,height:5},
 saco1520:{label:"Saco 15 × 20 × 5 cm",cost:.1,width:15,length:20,height:5}
};
const mlFreightBands=[
 [0,.3,[5.65,6.55,7.75,12.35,14.35,16.45,18.45,20.95]],[.3,.5,[5.95,6.65,7.85,13.25,15.45,17.65,19.85,22.55]],[.5,1,[6.05,6.75,7.95,13.85,16.15,18.45,20.75,23.65]],[1,1.5,[6.15,6.85,8.05,14.15,16.45,18.85,21.15,24.65]],
 [1.5,2,[6.25,6.95,8.15,14.45,16.85,19.25,21.65,24.65]],[2,3,[6.35,7.95,8.55,15.75,18.35,21.05,23.65,26.25]],[3,4,[6.45,8.15,8.95,17.05,19.85,22.65,25.55,28.35]],[4,5,[6.55,8.35,9.75,18.45,21.55,24.65,27.75,30.75]],
 [5,6,[6.65,8.55,9.95,25.45,28.55,32.65,35.75,39.75]],[6,7,[6.75,8.75,10.15,27.05,31.05,36.05,40.05,44.05]],[7,8,[6.85,8.95,10.35,28.85,33.65,38.45,43.25,48.05]],[8,9,[6.95,9.15,10.55,29.65,34.55,39.55,44.45,49.35]],
 [9,11,[7.05,9.55,10.95,41.25,48.05,54.95,61.75,68.65]],[11,13,[7.15,9.95,11.35,42.15,49.25,56.25,63.25,70.25]],[13,15,[7.25,10.35,11.75,43.25,50.45,57.65,65.05,72.25]],[15,999,[7.55,11.15,12.55,49.05,57.25,65.45,73.55,81.75]]
] as [number,number,number[]][];
const mlPriceLimits=[18.99,48.99,78.99,99.99,119.99,149.99,199.99,999999];
const defaultConfig:PriceConfig={margem:.15,imposto:.05,tacos:0,divisor_cubico:6000,ml_comissao_classico:.12,ml_comissao_premium:.17,shopee_faixas:[{min:0,max:79.99,comissao:.2,fixa:4},{min:80,max:99.99,comissao:.14,fixa:16},{min:100,max:199.99,comissao:.14,fixa:20},{min:200,max:499.99,comissao:.14,fixa:26},{min:500,max:999999999,comissao:.14,fixa:26}],ml_frete:mlFreightBands.map(([min,max,values])=>({min,max,frete:values.map((value,index)=>[mlPriceLimits[index],value])}))};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const parseDecimal=(value:unknown)=>{
 const raw=String(value??"").trim().replace(/\s/g,"");
 if(!raw)return 0;
 const normalized=raw.includes(",")?raw.replace(/\./g,"").replace(",","."):raw;
 const parsed=Number(normalized);
 return Number.isFinite(parsed)&&parsed>0?parsed:0;
};
const normalizeMeasure=(field:"weight"|"width"|"length"|"height",value:unknown)=>{
 let parsed=parseDecimal(value);
 // O Bling e etiquetas de fornecedores frequentemente informam peso em gramas.
 if(field==="weight"&&parsed>=100)parsed/=1000;
 // Medidas acima de 200 normalmente chegam em milímetros; o anúncio usa centímetros.
 if(field!=="weight"&&parsed>200)parsed/=10;
 return parsed?String(Math.round(parsed*100)/100):"";
};
const normalizeMeasures=(source:any)=>({
 ...source,
 weight:normalizeMeasure("weight",source.weight),
 width:normalizeMeasure("width",source.width),
 length:normalizeMeasure("length",source.length),
 height:normalizeMeasure("height",source.height)
});
export default function ListingCatalogView({isMaster=false}:{isMaster?:boolean}){
 const [items,setItems]=useState<Item[]>([]),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<Item|null>(null),[open,setOpen]=useState(false),[filter,setFilter]=useState("todos"),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[aiBusy,setAiBusy]=useState(false),[error,setError]=useState("");
 const [importOpen,setImportOpen]=useState(false),[importRows,setImportRows]=useState<ImportRow[]>([]),[importName,setImportName]=useState(""),[importError,setImportError]=useState("");
 const [aiSettingsOpen,setAiSettingsOpen]=useState(false),[aiConfigured,setAiConfigured]=useState(false);
 const [mlSettingsOpen,setMlSettingsOpen]=useState(false),[mlConnection,setMlConnection]=useState<MlConnection|null>(null);
 const [shopeeSettingsOpen,setShopeeSettingsOpen]=useState(false),[shopeeReconfigure,setShopeeReconfigure]=useState(false),[shopeeConnection,setShopeeConnection]=useState<ShopeeConnection|null>(null);
 const [blingSettingsOpen,setBlingSettingsOpen]=useState(false),[blingConnection,setBlingConnection]=useState<BlingConnection|null>(null);
 const [blingImportOpen,setBlingImportOpen]=useState(false),[blingProducts,setBlingProducts]=useState<BlingProduct[]>([]),[blingSelected,setBlingSelected]=useState<string[]>([]),[blingQuery,setBlingQuery]=useState(""),[blingPage,setBlingPage]=useState(1),[blingHasMore,setBlingHasMore]=useState(false),[blingBusy,setBlingBusy]=useState(false),[blingImportError,setBlingImportError]=useState("");
 const [catalogCandidates,setCatalogCandidates]=useState<CatalogCandidate[]>([]),[categorySuggestions,setCategorySuggestions]=useState<CategorySuggestion[]>([]),[categoryConfirmed,setCategoryConfirmed]=useState(false),[catalogBusy,setCatalogBusy]=useState(false),[publishBusy,setPublishBusy]=useState(false);
 const [shopeeCategories,setShopeeCategories]=useState<ShopeeCategory[]>([]),[shopeeLogistics,setShopeeLogistics]=useState<ShopeeLogistic[]>([]),[shopeeCatalogBusy,setShopeeCatalogBusy]=useState(false),[shopeeCategoryAuto,setShopeeCategoryAuto]=useState(false);
 const [shopeePublishNotice,setShopeePublishNotice]=useState<{kind:"loading"|"success"|"error";text:string}|null>(null);
 const [config,setConfig]=useState<PriceConfig>(defaultConfig);
 const fileInput=useRef<HTMLInputElement>(null);
 async function load(){const r=await fetch("/api/listings");if(r.ok){const d=await r.json();setItems(d.map((x:any)=>({...x,image_keys:JSON.parse(x.image_keys||"[]")})))}}
 async function loadMlConnection(){const r=await fetch("/api/marketplaces/mercado-livre/settings");if(r.ok)setMlConnection(await r.json())}
 async function loadShopeeConnection(){const r=await fetch("/api/marketplaces/shopee/settings");if(r.ok)setShopeeConnection(await r.json())}
 async function loadBlingConnection(){const r=await fetch("/api/marketplaces/bling/settings");if(r.ok)setBlingConnection(await r.json())}
 useEffect(()=>{load();loadMlConnection();loadShopeeConnection();loadBlingConnection();fetch("/api/listings/pricing-config").then(r=>r.ok?r.json():null).then(d=>{if(d)setConfig({...defaultConfig,...d})});fetch("/api/ai-settings").then(r=>r.ok?r.json():null).then(d=>setAiConfigured(Boolean(d?.configured)))},[]);
 function add(){setEditing(null);setForm(empty);setCatalogCandidates([]);setCategorySuggestions([]);setCategoryConfirmed(false);setError("");setOpen(true)}
 function edit(i:Item){setEditing(i);setCatalogCandidates([]);setCategorySuggestions([]);setCategoryConfirmed(false);setForm({sku:i.sku,productName:i.product_name,platform:i.platform,status:i.status,salePrice:i.sale_price||"",mlPrice:i.ml_price||"",shopeePrice:i.shopee_price||"",cost:i.cost||"",packagingCost:i.packaging_cost||"",extraCost:i.extra_cost||"",mlModality:i.ml_modality||"classico",title:i.title,description:i.description,mlTitle:i.ml_title||i.title||"",shopeeTitle:i.shopee_title||i.title||"",mlDescription:i.ml_description||i.description||"",shopeeDescription:i.shopee_description||i.description||"",packaging:i.packaging,weight:i.weight||"",width:i.width||"",length:i.length||"",height:i.height||"",imageKeys:i.image_keys,listingUrl:i.listing_url,gtin:i.gtin||"",brand:i.brand||"",model:i.model||"",packageVolume:i.package_volume||"",unitsPerPack:i.units_per_pack||1,stockQuantity:i.stock_quantity||1,mlCatalogProductId:i.ml_catalog_product_id||"",mlCategoryId:i.ml_category_id||"",mlItemId:i.ml_item_id||"",mlPermalink:i.ml_permalink||"",mlPublishStatus:i.ml_publish_status||"",mlError:i.ml_error||"",shopeeCategoryId:(i as any).shopee_category_id||"",shopeeLogisticId:(i as any).shopee_logistic_id||"",shopeeItemId:(i as any).shopee_item_id||"",shopeeError:(i as any).shopee_error||""});setError("");setOpen(true)}
 async function upload(files:FileList|null){if(!files?.length)return;const keys=[...form.imageKeys];for(const file of Array.from(files).slice(0,8-keys.length)){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/listing-images",{method:"POST",body:fd}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível enviar a imagem.");keys.push(d.key)}setForm((v:any)=>({...v,imageKeys:keys}))}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const corrected=normalizeMeasures(form);setForm(corrected);const r=await fetch(editing?`/api/listings/${editing.id}`:"/api/listings",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(corrected)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível salvar.");setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setBusy(false)}}
 async function remove(i:Item){if(!confirm(`Excluir o anúncio de "${i.product_name}"?`))return;const r=await fetch(`/api/listings/${i.id}`,{method:"DELETE"});if(r.ok)await load()}
 async function generateWithAi(){
  if(!form.productName){setError("Informe o nome do produto antes de gerar.");return}
  if(!form.imageKeys.length){setError("Envie pelo menos uma foto original do produto.");return}
  setAiBusy(true);setError("");
  try{
   const r=await fetch("/api/listings/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productName:form.productName,sku:form.sku,platform:form.platform,imageKey:form.imageKeys[0],existingImageKeys:form.imageKeys})});
   const raw=await r.text();let d:any={};if(raw){try{d=JSON.parse(raw)}catch{}}
   if(!r.ok)throw new Error(d.error||`A geração foi interrompida pelo servidor (erro ${r.status}). Tente novamente.`);
   if(!raw)throw new Error("A geração terminou sem resposta. Tente novamente em alguns instantes.");
   setForm((v:any)=>({...v,mlTitle:d.mlTitle,shopeeTitle:d.shopeeTitle,mlDescription:d.mlDescription,shopeeDescription:d.shopeeDescription,title:d.mlTitle||d.shopeeTitle,description:d.mlDescription||d.shopeeDescription,imageKeys:[v.imageKeys[0],...d.imageKeys].filter(Boolean).slice(0,6)}));
  }catch(e){setError(e instanceof Error?e.message:"Não foi possível gerar o anúncio.")}finally{setAiBusy(false)}
 }
 async function saveAiSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget),r=await fetch("/api/ai-settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({apiKey:data.get("apiKey")})}),d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Não foi possível configurar.");return}setAiConfigured(true);setAiSettingsOpen(false)}
 async function saveMlSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget),r=await fetch("/api/marketplaces/mercado-livre/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({clientId:data.get("clientId"),clientSecret:data.get("clientSecret")})}),d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Não foi possível salvar a integração.");return}await loadMlConnection();setMlSettingsOpen(false)}
 function connectMl(){window.location.href="/api/marketplaces/mercado-livre/authorize"}
 async function saveShopeeSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget),environment=String(data.get("environment")||"sandbox"),r=await fetch("/api/marketplaces/shopee/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({environment:data.get("environment"),partnerId:data.get("partnerId"),partnerKey:data.get("partnerKey")})}),d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Não foi possível salvar a integração com a Shopee.");return}await loadShopeeConnection();setShopeeReconfigure(false);setShopeeSettingsOpen(false);alert(`Credenciais da Shopee ${environment==="production"?"Produção":"Sandbox"} salvas. Agora clique em Conectar Shopee ${environment==="production"?"Produção":"Sandbox"} para autorizar a loja.`)}
 function connectShopee(){window.location.href="/api/marketplaces/shopee/authorize"}
 async function saveBlingSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=new FormData(e.currentTarget),r=await fetch("/api/marketplaces/bling/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({clientId:data.get("clientId"),clientSecret:data.get("clientSecret")})}),d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Não foi possível salvar a integração com o Bling.");return}await loadBlingConnection();setBlingSettingsOpen(false)}
 function connectBling(){window.location.href="/api/marketplaces/bling/authorize"}
 async function searchBling(page=1){setBlingBusy(true);setBlingImportError("");try{const r=await fetch(`/api/marketplaces/bling/products?q=${encodeURIComponent(blingQuery)}&page=${page}`),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível consultar os produtos do Bling.");setBlingProducts(d.products||[]);setBlingPage(page);setBlingHasMore(Boolean(d.hasMore))}catch(e){setBlingImportError(e instanceof Error?e.message:"Não foi possível consultar o Bling.")}finally{setBlingBusy(false)}}
 async function openBlingImport(){if(!blingConnection?.connected){setError("Conecte o Bling antes de importar produtos.");return}setBlingImportOpen(true);setBlingSelected([]);setBlingQuery("");setBlingProducts([]);setBlingImportError("");setTimeout(()=>searchBling(1),0)}
 function toggleBlingProduct(id:string){setBlingSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}
 async function importFromBling(){if(!blingSelected.length)return;setBlingBusy(true);setBlingImportError("");try{const r=await fetch("/api/marketplaces/bling/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ids:blingSelected})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível importar os produtos.");setBlingImportOpen(false);setBlingSelected([]);await load();alert(`${d.imported} produto(s) importado(s) do Bling.${d.skipped?` ${d.skipped} já existiam no catálogo.`:""}${d.failed?` ${d.failed} não puderam ser importados.`:""}`)}catch(e){setBlingImportError(e instanceof Error?e.message:"Não foi possível importar os produtos.")}finally{setBlingBusy(false)}}
 async function searchMlCatalog(){
  if(!form.gtin&&!form.productName){setError("Informe o GTIN ou o nome do produto.");return}
  setCatalogBusy(true);setError("");setCatalogCandidates([]);setCategorySuggestions([]);setCategoryConfirmed(false);setForm((v:any)=>({...v,mlCategoryId:""}));
  try{
   const r=await fetch("/api/marketplaces/mercado-livre/catalog",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({gtin:form.gtin,query:[form.productName,form.brand,form.model,form.packageVolume].filter(Boolean).join(" ")})});
   const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível buscar o catálogo.");
   setCatalogCandidates(d.candidates||[]);
   setCategorySuggestions(d.categories||[]);
   if(!(d.candidates||[]).length)setError("Nenhum catálogo compatível foi encontrado. Você poderá publicar sem catálogo usando a categoria sugerida.");
  }catch(e){setError(e instanceof Error?e.message:"Não foi possível buscar o catálogo.")}finally{setCatalogBusy(false)}
 }
 function chooseCatalog(candidate:CatalogCandidate){setForm((v:any)=>({...v,mlCatalogProductId:candidate.id,mlCategoryId:candidate.categoryId||v.mlCategoryId,brand:v.brand||candidate.brand,model:v.model||candidate.model,gtin:v.gtin||candidate.gtin,packageVolume:v.packageVolume||candidate.packageVolume}));if(candidate.categoryId)setCategoryConfirmed(true)}
 function chooseCategory(category:CategorySuggestion){setForm((v:any)=>({...v,mlCategoryId:category.id,mlCatalogProductId:""}));setCategoryConfirmed(true);setError("")}
 async function publishMl(mode:"catalog"|"traditional"){
  if(!editing){setError("Salve o anúncio antes da primeira publicação.");return}
  if(!confirm(mode==="catalog"?"Publicar este produto no catálogo selecionado do Mercado Livre?":"Publicar como anúncio tradicional, sem catálogo?"))return;
  setPublishBusy(true);setError("");setForm((v:any)=>({...v,mlError:""}));
  try{
   const prepared={...form,mlPrice:form.mlPrice||suggestedMl,salePrice:form.salePrice||(form.platform==="mercado_livre"?suggestedMl:Math.max(suggestedMl,suggestedShopee))};
   setForm(prepared);
   const saved=await fetch(`/api/listings/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(prepared)}),savedData=await saved.json();
   if(!saved.ok)throw new Error(savedData.error||"Não foi possível salvar antes de publicar.");
   const r=await fetch("/api/marketplaces/mercado-livre/publish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.id,mode,price:prepared.mlPrice,stockQuantity:prepared.stockQuantity,mlModality:prepared.mlModality,sku:prepared.sku,mlCatalogProductId:prepared.mlCatalogProductId,mlCategoryId:prepared.mlCategoryId,imageKeys:prepared.imageKeys,gtin:prepared.gtin,brand:prepared.brand,model:prepared.model,packageVolume:prepared.packageVolume,productName:prepared.productName,familyName:[prepared.brand,prepared.model,prepared.packageVolume].filter(Boolean).join(" "),weight:prepared.weight,width:prepared.width,length:prepared.length,height:prepared.height,mlTitle:prepared.mlTitle,title:prepared.title,mlDescription:prepared.mlDescription,description:prepared.description})}),d=await r.json();
   if(!r.ok)throw new Error(d.error||"Não foi possível publicar.");
   setForm((v:any)=>({...v,status:"publicado",listingUrl:d.permalink,mlPermalink:d.permalink,mlItemId:d.itemId,mlPublishStatus:d.status,mlError:""}));
   await load();alert(`Anúncio publicado com sucesso. ID ${d.itemId}`);
  }catch(e){const message=e instanceof Error?e.message:"Não foi possível publicar.";setError(message);setForm((v:any)=>({...v,mlPublishStatus:"erro",mlError:message}));alert(`O Mercado Livre recusou a publicação:\n\n${message}`)}finally{setPublishBusy(false)}
 }
 async function loadShopeeCatalog(){
  setShopeeCatalogBusy(true);setError("");try{const itemName=[form.shopeeTitle||form.title||form.productName,form.brand,form.model].filter(Boolean).join(" "),r=await fetch(`/api/marketplaces/shopee/catalog?itemName=${encodeURIComponent(itemName)}`),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível consultar a Shopee.");setShopeeCategories(d.categories||[]);setShopeeLogistics(d.logistics||[]);if(!(d.categories||[]).length)throw new Error("A Shopee não retornou categorias para esta loja de teste.");if(!form.shopeeCategoryId&&d.recommendedCategoryId){setForm((current:any)=>({...current,shopeeCategoryId:String(d.recommendedCategoryId)}));setShopeeCategoryAuto(true)}}catch(e){setError(e instanceof Error?e.message:"Não foi possível consultar a Shopee.")}finally{setShopeeCatalogBusy(false)}
 }
 async function prepareShopeeImages(keys:string[]){
  const converted:string[]=[];
  for(let index=0;index<keys.length;index++){
   const response=await fetch(`/api/listing-images/${keys[index]}`);if(!response.ok)throw new Error(`Não foi possível preparar a imagem ${index+1}.`);const bitmap=await createImageBitmap(await response.blob()),size=1600,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const context=canvas.getContext("2d");if(!context)throw new Error("O navegador não conseguiu converter as imagens.");context.fillStyle="#ffffff";context.fillRect(0,0,size,size);const scale=Math.min((size*0.9)/bitmap.width,(size*0.9)/bitmap.height),width=bitmap.width*scale,height=bitmap.height*scale;context.drawImage(bitmap,(size-width)/2,(size-height)/2,width,height);bitmap.close();const jpeg=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Não foi possível converter uma das imagens para JPG.")),"image/jpeg",.92));const data=new FormData();data.append("file",new File([jpeg],`${form.sku||"produto"}-shopee-${index+1}.jpg`,{type:"image/jpeg"}));const uploaded=await fetch("/api/listing-images",{method:"POST",body:data}),result=await uploaded.json();if(!uploaded.ok)throw new Error(result.error||"Não foi possível salvar a imagem preparada para a Shopee.");converted.push(result.key)
  }
  return converted;
 }
 async function publishShopee(){
  if(!editing){setError("Salve o anúncio e abra novamente para publicar.");return}if(!confirm(`Publicar este produto na Shopee ${shopeeConnection?.environment==="sandbox"?"Sandbox":""}?`))return;
  setPublishBusy(true);setError("");setShopeePublishNotice({kind:"loading",text:"Enviando produto e imagens para a Shopee…"});try{const shopeeImageKeys=await prepareShopeeImages(form.imageKeys);const prepared={...form,imageKeys:shopeeImageKeys,shopeePrice:form.shopeePrice||suggestedShopee,salePrice:form.salePrice||(form.platform==="shopee"?suggestedShopee:Math.max(suggestedMl,suggestedShopee))};setForm(prepared);const saved=await fetch(`/api/listings/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(prepared)}),savedData=await saved.json();if(!saved.ok)throw new Error(savedData.error||"Não foi possível salvar antes de publicar.");const r=await fetch("/api/marketplaces/shopee/publish",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.id,categoryId:prepared.shopeeCategoryId,logisticId:prepared.shopeeLogisticId,title:prepared.shopeeTitle||prepared.title,description:prepared.shopeeDescription||prepared.description,sku:prepared.sku,brand:prepared.brand||"Sem marca",price:prepared.shopeePrice,stockQuantity:prepared.stockQuantity,weight:prepared.weight,width:prepared.width,length:prepared.length,height:prepared.height,imageKeys:prepared.imageKeys})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível publicar na Shopee.");setForm((v:any)=>({...v,status:"publicado",shopeeItemId:d.itemId,shopeeError:""}));setShopeePublishNotice({kind:"success",text:`Publicado com sucesso na Shopee. ID ${d.itemId}`});await load()}catch(e){const message=e instanceof Error?e.message:"Não foi possível publicar na Shopee.";setError(message);setForm((v:any)=>({...v,shopeeError:message}));setShopeePublishNotice({kind:"error",text:`A Shopee recusou a publicação: ${message}`})}finally{setPublishBusy(false)}
 }
 function downloadImage(key:string,index:number){const a=document.createElement("a"),ext=key.split(".").pop()||"jpg";a.href=`/api/listing-images/${key}?download=1`;a.download=`${form.sku||"produto"}-${index===0?"original":`imagem-${index}`}.${ext}`;document.body.appendChild(a);a.click();a.remove()}
 function downloadAll(){form.imageKeys.forEach((key:string,index:number)=>setTimeout(()=>downloadImage(key,index),index*250))}
 function selectPackage(id:string){const p=packages[id];setForm((v:any)=>p?{...v,packaging:id,packagingCost:p.cost,width:p.width,length:p.length,height:p.height}:{...v,packaging:"",packagingCost:"",width:"",length:"",height:""})}
 const n=(value:unknown)=>Number(value)||0;
 const cubicWeight=n(form.width)*n(form.length)*n(form.height)/(config.divisor_cubico||6000);
 const chargedWeight=Math.max(n(form.weight),cubicWeight);
 const baseCost=n(form.cost)+n(form.packagingCost)+n(form.extraCost);
 function mlFreight(price:number){
  if(!config.ml_frete?.length)return 0;
  const band=config.ml_frete.find(f=>chargedWeight<=f.max)||config.ml_frete[config.ml_frete.length-1];
  return (band.frete.find(f=>price<=f[0])||band.frete[band.frete.length-1])?.[1]||0;
 }
 function calcMl(){
  if(!n(form.cost))return 0;const commission=form.mlModality==="premium"?config.ml_comissao_premium:config.ml_comissao_classico;
  let price=baseCost/(1-commission-config.imposto-config.tacos-config.margem);
  for(let i=0;i<20;i++)price=(baseCost+mlFreight(price))/(1-commission-config.imposto-config.tacos-config.margem);
  return Math.ceil(price*100)/100;
 }
 function calcShopee(){
  if(!n(form.cost))return 0;let price=baseCost/(1-.14-config.imposto-config.tacos-config.margem);
  for(let i=0;i<30;i++){const band=config.shopee_faixas.find(f=>price>=f.min&&price<=f.max)||config.shopee_faixas[config.shopee_faixas.length-1];price=(baseCost+band.fixa)/(1-band.comissao-config.imposto-config.tacos-config.margem)}
  return Math.ceil(price*100)/100;
 }
 const suggestedMl=calcMl(),suggestedShopee=calcShopee();
 function applyPrices(){setForm((v:any)=>({...v,mlPrice:suggestedMl||"",shopeePrice:suggestedShopee||"",salePrice:v.platform==="mercado_livre"?suggestedMl:v.platform==="shopee"?suggestedShopee:Math.max(suggestedMl,suggestedShopee)}))}
 const key=(value:unknown)=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
 const value=(row:Record<string,unknown>,aliases:string[])=>{const found=Object.entries(row).find(([k])=>aliases.includes(key(k)));return found?.[1]??""};
 const decimal=(v:unknown)=>{if(typeof v==="number")return String(v);const s=String(v??"").trim().replace(/\s/g,"");if(!s)return"";return s.includes(",")?s.replace(/\./g,"").replace(",","."):s};
 async function chooseFile(files:FileList|null){
  const file=files?.[0];if(!file)return;setImportError("");setImportRows([]);setImportName(file.name);
  try{
   const XLSX=await import("xlsx");
   const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"});
   const sheet=workbook.Sheets[workbook.SheetNames[0]];
   const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:"",raw:false});
   if(!raw.length)throw new Error("O arquivo não possui produtos.");
   const parsed=raw.slice(0,1000).map((r,index)=>{
    const productName=String(value(r,["descricao","nome","produto","nomedoproduto","description"])).trim();
    return{row:index+2,sku:String(value(r,["codigo","sku","codigoproduto","codigodoproduto"])).trim(),productName,
     salePrice:decimal(value(r,["preco","precovenda","precodevenda","valor","price"])),
     weight:normalizeMeasure("weight",decimal(value(r,["peso","pesobruto","pesoliquido","weight"]))),
     width:normalizeMeasure("width",decimal(value(r,["largura","width"]))),length:normalizeMeasure("length",decimal(value(r,["comprimento","profundidade","length"]))),
     height:normalizeMeasure("height",decimal(value(r,["altura","height"]))),valid:Boolean(productName)};
   });
   setImportRows(parsed);setImportOpen(true);
  }catch(e){setImportError(e instanceof Error?e.message:"Não foi possível ler o arquivo.");setImportOpen(true)}
  finally{if(fileInput.current)fileInput.current.value=""}
 }
 async function confirmImport(){
  const rows=importRows.filter(r=>r.valid);if(!rows.length)return;setBusy(true);setImportError("");
  try{
   const r=await fetch("/api/listings/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows})});
   const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível importar.");
   setImportOpen(false);setImportRows([]);await load();
   alert(`${d.imported} produto(s) importado(s).${d.skipped?` ${d.skipped} SKU(s) já existente(s) foram ignorados.`:""}`);
  }catch(e){setImportError(e instanceof Error?e.message:"Não foi possível importar.")}finally{setBusy(false)}
 }
 const visible=items.filter(i=>(filter==="todos"||i.status===filter)&&`${i.product_name} ${i.sku} ${i.title}`.toLowerCase().includes(search.toLowerCase())),count=(s:string)=>items.filter(i=>i.status===s).length;
 return <div className="listings-area"><header className="listings-head"><div><p className="eyebrow">FLUXO DE PUBLICAÇÃO</p><h1>Catálogo de Anúncios</h1><p>Prepare e publique anúncios diretamente no Mercado Livre e na Shopee.</p></div><div className="head-actions"><input ref={fileInput} className="import-file" type="file" accept=".csv,.xls,.xlsx" onChange={e=>chooseFile(e.target.files)}/>{isMaster&&<button className={`secondary ai-config-status ${aiConfigured?"ready":""}`} onClick={()=>{setError("");setAiSettingsOpen(true)}}>{aiConfigured?"● IA conectada":"⚙ Configurar IA"}</button>}{blingConnection?.connected?<button className="secondary marketplace-connected" onClick={()=>setBlingSettingsOpen(true)}>● Bling conectado</button>:blingConnection?.configured?<button className="secondary marketplace-connect" onClick={connectBling}>Conectar Bling</button>:isMaster?<button className="secondary marketplace-connect" onClick={()=>{setError("");setBlingSettingsOpen(true)}}>⚙ Configurar Bling</button>:null}{mlConnection?.connected?<button className="secondary marketplace-connected" onClick={()=>setMlSettingsOpen(true)}>● Mercado Livre conectado</button>:mlConnection?.configured?<button className="secondary marketplace-connect" onClick={connectMl}>Conectar Mercado Livre</button>:isMaster?<button className="secondary marketplace-connect" onClick={()=>{setError("");setMlSettingsOpen(true)}}>⚙ Configurar Mercado Livre</button>:null}{shopeeConnection?.connected?<button className="secondary marketplace-connected" onClick={()=>setShopeeSettingsOpen(true)}>● Shopee {shopeeConnection.environment==="sandbox"?"Sandbox ":""}conectada</button>:shopeeConnection?.configured?<><button className="secondary marketplace-connect" onClick={connectShopee}>Conectar Shopee {shopeeConnection.environment==="production"?"Produção":"Sandbox"}</button>{isMaster&&<button className="secondary marketplace-connect" onClick={()=>{setError("");setShopeeSettingsOpen(true)}}>⚙ Shopee</button>}</>:isMaster?<button className="secondary marketplace-connect" onClick={()=>{setError("");setShopeeSettingsOpen(true)}}>⚙ Configurar Shopee</button>:null}{blingConnection?.connected&&<button className="primary bling-import-button" onClick={openBlingImport}>⇩ Importar do Bling</button>}<button className="secondary" onClick={()=>fileInput.current?.click()}>⇧ Importar planilha</button><button className="primary" onClick={add}>+ Novo anúncio</button></div></header>
 <section className="listing-stats"><div><strong>{items.length}</strong><span>Total</span></div><div><strong>{count("preparacao")}</strong><span>Em preparação</span></div><div><strong>{count("pronto")}</strong><span>Prontos</span></div><div><strong>{count("publicado")}</strong><span>Publicados</span></div></section>
 <section className="panel listing-panel"><div className="catalog-tools"><div className="filter-chips">{[["todos","Todos"],["preparacao","Em preparação"],["pronto","Prontos"],["publicado","Publicados"]].map(([k,l])=><button key={k} className={filter===k?"filter-chip selected":"filter-chip"} onClick={()=>setFilter(k)}>{l}</button>)}</div><input className="catalog-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar produto, SKU ou título…"/></div><div className="listing-grid">{visible.map(i=><article className="listing-card" key={i.id}>{i.image_keys[0]?<img src={`/api/listing-images/${i.image_keys[0]}`} alt={i.product_name}/>:<div className="listing-placeholder">SEM FOTO</div>}<div className="listing-card-body"><div className="listing-badges"><span className={`listing-status ${i.status}`}>{statuses[i.status]}</span><span className="listing-platform">{platforms[i.platform]}</span></div><small>SKU {i.sku||"não informado"}</small><h2>{i.product_name}</h2><p>{i.title||"Título ainda não preparado."}</p>{i.platform==="ambos"&&(i.ml_price||i.shopee_price)?<div className="market-prices"><span>ML <b>{i.ml_price?money(i.ml_price):"—"}</b></span><span>Shopee <b>{i.shopee_price?money(i.shopee_price):"—"}</b></span></div>:null}<div className="listing-bottom"><strong>{i.sale_price?money(i.sale_price):"Preço pendente"}</strong><div><button className="icon-btn" onClick={()=>edit(i)} aria-label="Editar anúncio">✎</button><button className="icon-btn danger" onClick={()=>remove(i)} aria-label="Excluir anúncio">×</button></div></div></div></article>)}{!visible.length&&<div className="empty"><span>✓</span><p>Nenhum anúncio encontrado. Cadastre o primeiro produto.</p></div>}</div></section>
 {open&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="modal modal-wide"><div className="modal-head"><h2>{editing?"Editar anúncio":"Novo anúncio"}</h2><button onClick={()=>setOpen(false)}>×</button></div><form className="listing-form" onSubmit={save}>
 <div className="form-grid"><label>Nome do produto<input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} placeholder="Ex.: Aluminium Nitro 1,5L"/></label><label>SKU do Bling<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label></div>
 <div className="form-grid"><label>Plataforma<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option value="shopee">Shopee</option><option value="mercado_livre">Mercado Livre</option><option value="ambos">Shopee + Mercado Livre</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="preparacao">Em preparação</option><option value="pronto">Pronto para publicar</option><option value="publicado">Publicado</option></select></label></div>
 <section className="pricing-box"><div className="pricing-box-head"><div><strong>Preço e embalagem</strong><span>Use os mesmos cálculos da tela Preço E-commerce.</span></div><span className="margin-chip">Margem-alvo {(config.margem*100).toFixed(0)}%</span></div>
 <div className="form-grid"><label>Custo do produto (R$)<input type="number" min="0" step=".01" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/></label><label>Custos adicionais (R$)<input type="number" min="0" step=".01" value={form.extraCost} onChange={e=>setForm({...form,extraCost:e.target.value})}/></label></div>
 <div className="form-grid"><label>Embalagem padrão<select value={form.packaging} onChange={e=>selectPackage(e.target.value)}><option value="">Selecione a embalagem</option>{Object.entries(packages).map(([id,p])=><option value={id} key={id}>{p.label}</option>)}</select></label><label>Custo da embalagem (R$)<input type="number" min="0" step=".01" value={form.packagingCost} onChange={e=>setForm({...form,packagingCost:e.target.value})}/></label></div>
 <div className="form-grid"><label>Tipo de anúncio Mercado Livre<select value={form.mlModality} onChange={e=>setForm({...form,mlModality:e.target.value})}><option value="classico">Clássico</option><option value="premium">Premium</option></select></label><label>Preço atual/importado (R$)<input type="number" min="0" step=".01" value={form.salePrice} onChange={e=>setForm({...form,salePrice:e.target.value})}/></label></div>
 </section>
 <section className="ai-generator"><div><span className="ai-spark">✦</span><strong>Criação automática do anúncio</strong><p>A IA analisa a foto, prepara os textos para cada plataforma e cria cinco imagens comerciais — seis imagens no total com a original.</p></div><button type="button" className="ai-button" disabled={aiBusy||!form.productName||!form.imageKeys.length} onClick={generateWithAi}>{aiBusy?"Gerando… pode levar até 3 minutos":"✦ Gerar título, descrição e 5 imagens"}</button></section>
 <div className="platform-copy-grid"><section><div className="copy-head ml-copy">MERCADO LIVRE</div><label>Título para Mercado Livre<input maxLength={60} value={form.mlTitle} onChange={e=>setForm({...form,mlTitle:e.target.value,title:e.target.value})}/></label><label>Descrição para Mercado Livre<textarea value={form.mlDescription} onChange={e=>setForm({...form,mlDescription:e.target.value,description:e.target.value})}/></label></section><section><div className="copy-head shopee-copy">SHOPEE</div><label>Título para Shopee<input maxLength={120} value={form.shopeeTitle} onChange={e=>setForm({...form,shopeeTitle:e.target.value})}/></label><label>Descrição para Shopee<textarea value={form.shopeeDescription} onChange={e=>setForm({...form,shopeeDescription:e.target.value})}/></label></section></div>
 {(form.platform==="mercado_livre"||form.platform==="ambos")&&<section className="ml-publish-box">
  <div className="ml-publish-head"><div><strong>Publicação direta no Mercado Livre</strong><span>Identifique o produto, encontre o catálogo correto e publique sem passar pelo Bling.</span></div>{form.mlItemId?<span className="ml-live">● Publicado</span>:mlConnection?.connected?<span className="ml-ready">API conectada</span>:<span className="ml-offline">API desconectada</span>}</div>
  {!mlConnection?.connected&&<div className="form-error">{mlConnection?.lastError?`Mercado Livre: ${mlConnection.lastError}`:"A conta do Mercado Livre não foi confirmada nesta sessão. Feche o anúncio e use “Conectar Mercado Livre” no cabeçalho."}</div>}
  <div className="form-grid"><label>GTIN / código de barras<input value={form.gtin} inputMode="numeric" onChange={e=>setForm({...form,gtin:e.target.value.replace(/\D/g,"")})} placeholder="Ex.: 7890000000000"/></label><label>Marca<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Ex.: Nitro"/></label></div>
  <div className="form-grid"><label>Modelo ou linha<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} placeholder="Ex.: Aluminium"/></label><label>Volume da embalagem<input value={form.packageVolume} onChange={e=>setForm({...form,packageVolume:e.target.value})} placeholder="Ex.: 1,5 L"/></label></div>
  <div className="form-grid"><label>Quantidade por anúncio<input type="number" min="1" step="1" value={form.unitsPerPack} onChange={e=>setForm({...form,unitsPerPack:e.target.value})}/></label><label>Estoque inicial no anúncio<input type="number" min="1" step="1" value={form.stockQuantity} onChange={e=>setForm({...form,stockQuantity:e.target.value})}/></label></div>
  {!form.mlItemId&&<><div className="catalog-search-row"><button type="button" className="secondary" disabled={catalogBusy} onClick={searchMlCatalog}>{catalogBusy?"Pesquisando…":"⌕ Localizar no catálogo"}</button><span>{form.mlCatalogProductId?`Catálogo selecionado: ${form.mlCatalogProductId}`:"Pesquise preferencialmente pelo GTIN."}</span></div>
  {!!catalogCandidates.length&&<div className="catalog-candidates">{catalogCandidates.map(candidate=><button type="button" key={candidate.id} className={form.mlCatalogProductId===candidate.id?"catalog-candidate selected":"catalog-candidate"} onClick={()=>chooseCatalog(candidate)}>{candidate.picture?<img src={candidate.picture} alt=""/>:<span className="catalog-no-image">SEM FOTO</span>}<div><strong>{candidate.name}</strong><small>{[candidate.brand,candidate.model,candidate.packageVolume].filter(Boolean).join(" · ")||candidate.domainId}</small><em>{candidate.id}</em></div><b>{form.mlCatalogProductId===candidate.id?"✓ Escolhido":"Escolher"}</b></button>)}</div>}
  {!!categorySuggestions.length&&<section className="category-confirmation"><div><strong>Escolha obrigatoriamente a categoria correta</strong><span>Confira o caminho completo. A intranet não escolherá automaticamente.</span></div><div className="category-options">{categorySuggestions.map(category=><button type="button" key={category.id} className={categoryConfirmed&&form.mlCategoryId===category.id?"category-option selected":"category-option"} onClick={()=>chooseCategory(category)}><span>{category.path}</span><small>{category.id}{category.requiredAttributes.length?` · ${category.requiredAttributes.length} atributos obrigatórios`:""}</small><b>{categoryConfirmed&&form.mlCategoryId===category.id?"✓ Confirmada":"Confirmar categoria"}</b></button>)}</div></section>}
  <div className="publish-choice"><button type="button" className="primary ml-publish-button" disabled={!mlConnection?.connected||publishBusy||!editing||!form.mlCatalogProductId||!form.mlCategoryId||!categoryConfirmed} onClick={()=>publishMl("catalog")}>{publishBusy?"Publicando…":"Publicar no catálogo"}</button><button type="button" className="secondary" disabled={!mlConnection?.connected||publishBusy||!editing||!form.mlCategoryId||!categoryConfirmed} onClick={()=>publishMl("traditional")}>Publicar sem catálogo</button>{!categoryConfirmed&&<small>Localize e confirme uma categoria antes de publicar.</small>}{!editing&&<small>Salve o anúncio e abra novamente para publicar.</small>}</div></>}
  {form.mlItemId&&<div className="published-result"><div><strong>Anúncio {form.mlItemId}</strong><span>Status: {form.mlPublishStatus||"publicado"}</span></div>{form.mlPermalink&&<a href={form.mlPermalink} target="_blank" rel="noopener noreferrer">Abrir no Mercado Livre ↗</a>}</div>}
 {form.mlError&&<div className="form-error">{form.mlError}</div>}
 </section>}
 {(form.platform==="shopee"||form.platform==="ambos")&&<section className="shopee-publish-box">
  <div className="ml-publish-head"><div><strong>Publicação direta na Shopee</strong><span>Escolha a categoria e a forma de envio para publicar sem sair da intranet.</span></div>{form.shopeeItemId?<span className="ml-live">● Publicado</span>:shopeeConnection?.connected?<span className="shopee-ready">{shopeeConnection.environment==="sandbox"?"Sandbox conectada":"API conectada"}</span>:<span className="ml-offline">API desconectada</span>}</div>
  {!shopeeConnection?.connected&&<div className="form-error">Conecte a Shopee no cabeçalho antes de publicar.</div>}
  {shopeeConnection?.environment==="sandbox"&&<div className="import-note"><strong>Ambiente de teste da Shopee</strong><p>O Sandbox não possui o catálogo oficial do Brasil. A intranet oculta as categorias técnicas e mostra somente opções utilizáveis no teste. As categorias brasileiras reais aparecerão após o Go-live.</p></div>}
  {!form.shopeeItemId&&<><div className="catalog-search-row"><button type="button" className="secondary" disabled={!shopeeConnection?.connected||shopeeCatalogBusy} onClick={loadShopeeCatalog}>{shopeeCatalogBusy?"Carregando…":"Carregar categorias e envios"}</button><span>A lista vem diretamente da conta Shopee conectada.</span></div>
  <div className="form-grid"><label>Marca para Shopee<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} placeholder="Ex.: Nitro"/><small>Obrigatória na Shopee. Se o produto não tiver marca, informe “Sem marca”.</small></label>{!!shopeeCategories.length&&<label>Categoria Shopee<select value={form.shopeeCategoryId} onChange={e=>{setForm({...form,shopeeCategoryId:e.target.value});setShopeeCategoryAuto(false)}}><option value="">Selecione a categoria</option>{shopeeCategories.filter(c=>!c.hasChildren).map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select>{shopeeCategoryAuto&&<small>Categoria sugerida automaticamente pela Shopee. Você pode trocar se necessário.</small>}</label>}</div>
  {!!shopeeCategories.length&&<div className="form-grid"><label>Forma de envio<select value={form.shopeeLogisticId} onChange={e=>setForm({...form,shopeeLogisticId:e.target.value})}><option value="">Selecione a forma de envio</option>{shopeeLogistics.map(logistic=><option value={logistic.id} key={logistic.id}>{logistic.name}</option>)}</select></label></div>}
  <div className="publish-choice"><button type="button" className="primary shopee-publish-button" disabled={!shopeeConnection?.connected||publishBusy||!editing||!form.shopeeCategoryId||!form.shopeeLogisticId} onClick={publishShopee}>{publishBusy?"Publicando…":`Publicar na Shopee${shopeeConnection?.environment==="sandbox"?" Sandbox":""}`}</button>{!editing&&<small>Salve o anúncio e abra novamente para publicar.</small>}{editing&&!form.shopeeCategoryId&&<small>Carregue e selecione a categoria e o envio.</small>}</div></>}
  {shopeePublishNotice&&<div className={shopeePublishNotice.kind==="error"?"form-error":shopeePublishNotice.kind==="success"?"connection-success":"import-note"}><strong>{shopeePublishNotice.kind==="loading"?"Publicação em andamento":shopeePublishNotice.kind==="success"?"✓ Publicação concluída":"Publicação não concluída"}</strong><p>{shopeePublishNotice.text}</p></div>}
  {form.shopeeItemId&&<div className="published-result"><div><strong>Produto Shopee {form.shopeeItemId}</strong><span>Publicado com sucesso</span></div></div>}{form.shopeeError&&<div className="form-error">{form.shopeeError}</div>}
 </section>}
 <div className="measure-form">{([["weight","Peso (kg)"],["width","Largura (cm)"],["length","Comprimento (cm)"],["height","Altura (cm)"]] as const).map(([k,l])=><label key={k}>{l}<input inputMode="decimal" min="0" value={form[k]} readOnly={k!=="weight"&&Boolean(form.packaging)} onChange={e=>setForm({...form,[k]:e.target.value})} onBlur={e=>setForm((v:any)=>({...v,[k]:normalizeMeasure(k,e.target.value)}))}/></label>)}</div>
 <div className="weight-note"><span>Correção automática: <b>1500 g vira 1,5 kg</b></span>{form.packaging&&<span>As medidas seguem a <b>embalagem selecionada</b></span>}</div>
 <div className="weight-note"><span>Peso cúbico <b>{cubicWeight.toFixed(2)} kg</b></span><span>Peso considerado <b>{chargedWeight.toFixed(2)} kg</b></span></div>
 <section className="price-results"><div className="price-result ml-result"><small>MERCADO LIVRE</small><strong>{suggestedMl?money(suggestedMl):"Informe o custo"}</strong><span>{form.mlModality==="premium"?"Premium":"Clássico"} · frete estimado {money(mlFreight(suggestedMl))}</span></div><div className="price-result shopee-result"><small>SHOPEE</small><strong>{suggestedShopee?money(suggestedShopee):"Informe o custo"}</strong><span>Comissão e taxa fixa incluídas</span></div><button type="button" className="secondary apply-price" disabled={!suggestedMl&&!suggestedShopee} onClick={applyPrices}>Aplicar preços sugeridos</button></section>
 <label>Foto original do produto<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={async e=>{try{await upload(e.target.files)}catch(e){setError(e instanceof Error?e.message:"Erro ao enviar imagem.")}}}/><small>Envie primeiro a foto original. Depois use o botão de IA para criar as imagens do anúncio.</small></label>
 {!!form.imageKeys.length&&<><div className="image-strip-head"><span>{form.imageKeys.length} imagens · próximas gerações em 2000 × 2000 px</span><button type="button" className="secondary" onClick={downloadAll}>⇩ Baixar todas</button></div><div className="listing-image-strip">{form.imageKeys.map((k:string,index:number)=><div key={k}><span className="image-kind">{index===0?"ORIGINAL":"IA"}</span><img src={`/api/listing-images/${k}`} alt={index===0?"Foto original":"Imagem gerada por IA"}/><button className="image-remove" type="button" onClick={()=>setForm({...form,imageKeys:form.imageKeys.filter((x:string)=>x!==k)})} aria-label="Excluir imagem">×</button><button className="image-download" type="button" onClick={()=>downloadImage(k,index)} aria-label="Baixar imagem">⇩</button></div>)}</div></>}
 <label>Link do anúncio publicado<input type="url" value={form.listingUrl} onChange={e=>setForm({...form,listingUrl:e.target.value})}/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Salvando…":"Salvar anúncio"}</button></div></form></div></div>}
 {blingImportOpen&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setBlingImportOpen(false)}}><div className="modal modal-wide bling-import-modal"><div className="modal-head"><div><h2>Importar produtos do Bling</h2><small>Selecione os produtos que entrarão no Catálogo de Anúncios</small></div><button onClick={()=>setBlingImportOpen(false)}>×</button></div>
  <form className="bling-search-row" onSubmit={e=>{e.preventDefault();searchBling(1)}}><input value={blingQuery} onChange={e=>setBlingQuery(e.target.value)} placeholder="Buscar por nome, SKU ou código de barras…" autoFocus/><button className="primary" disabled={blingBusy}>{blingBusy?"Consultando…":"Buscar no Bling"}</button></form>
  {blingImportError&&<div className="form-error">{blingImportError}</div>}
  <div className="bling-selection-head"><label><input type="checkbox" checked={Boolean(blingProducts.length)&&blingProducts.every(product=>blingSelected.includes(product.id))} onChange={e=>setBlingSelected(e.target.checked?Array.from(new Set([...blingSelected,...blingProducts.map(product=>product.id)])):blingSelected.filter(id=>!blingProducts.some(product=>product.id===id)))}/> Selecionar os 50 produtos desta página</label><strong>{blingSelected.length} selecionado(s)</strong></div>
  <div className="bling-product-list">{blingProducts.map(product=><label className={blingSelected.includes(product.id)?"bling-product selected":"bling-product"} key={product.id}><input type="checkbox" checked={blingSelected.includes(product.id)} onChange={()=>toggleBlingProduct(product.id)}/>{product.picture?<img src={product.picture} alt=""/>:<span className="bling-no-photo">SEM FOTO</span>}<div><strong>{product.name}</strong><span>SKU {product.sku||"não informado"}{product.gtin?` · GTIN ${product.gtin}`:""}</span><small>{product.salePrice?money(product.salePrice):"Preço não informado"}{product.brand?` · ${product.brand}`:""}</small></div><em>{product.status==="A"?"Ativo":product.status||"Produto"}</em></label>)}{!blingBusy&&!blingProducts.length&&!blingImportError&&<div className="empty"><span>⇩</span><p>Busque um produto ou carregue a lista do Bling.</p></div>}</div>
  <div className="bling-pages"><button className="secondary" disabled={blingBusy||blingPage<=1} onClick={()=>searchBling(blingPage-1)}>← Anterior</button><span>Página {blingPage}</span><button className="secondary" disabled={blingBusy||!blingHasMore} onClick={()=>searchBling(blingPage+1)}>Próxima →</button></div>
  <div className="import-note"><strong>Dados trazidos automaticamente</strong><p>Nome, ID do Bling, SKU, código de barras, preço, custo, estoque, peso, medidas, marca e foto, quando estiverem cadastrados no produto.</p></div>
  <div className="modal-actions"><button className="secondary" onClick={()=>setBlingImportOpen(false)}>Cancelar</button><button className="primary" disabled={blingBusy||!blingSelected.length} onClick={importFromBling}>{blingBusy?"Importando…":`Importar ${blingSelected.length} produto(s)`}</button></div>
 </div></div>}
 {importOpen&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setImportOpen(false)}}><div className="modal modal-wide import-modal"><div className="modal-head"><div><h2>Importar produtos</h2><small>{importName}</small></div><button onClick={()=>setImportOpen(false)}>×</button></div>
  <div className="import-note"><strong>Como funciona</strong><p>A planilha deve ter pelo menos a coluna <b>Descrição</b> ou <b>Nome</b>. Também reconhecemos Código/SKU, preço, peso, largura, comprimento e altura. Os produtos entram como “Em preparação” para a equipe completar o anúncio.</p></div>
  {importError&&<div className="form-error">{importError}</div>}
  {!!importRows.length&&<><div className="import-summary"><strong>{importRows.filter(r=>r.valid).length} produtos prontos para importar</strong><span>{importRows.filter(r=>!r.valid).length} linhas sem nome serão ignoradas</span></div><div className="import-table-wrap"><table className="import-table"><thead><tr><th>Linha</th><th>SKU</th><th>Produto</th><th>Preço</th><th>Medidas (L×C×A)</th><th>Situação</th></tr></thead><tbody>{importRows.slice(0,100).map(r=><tr key={r.row} className={r.valid?"":"invalid"}><td>{r.row}</td><td>{r.sku||"—"}</td><td>{r.productName||"Nome não identificado"}</td><td>{r.salePrice?`R$ ${Number(r.salePrice).toLocaleString("pt-BR",{minimumFractionDigits:2})}`:"—"}</td><td>{r.width||"—"} × {r.length||"—"} × {r.height||"—"}</td><td><span>{r.valid?"Pronto":"Ignorar"}</span></td></tr>)}</tbody></table>{importRows.length>100&&<small className="import-more">Prévia das primeiras 100 linhas. Todas as {importRows.length} linhas serão processadas.</small>}</div></>}
 <div className="modal-actions"><button className="secondary" onClick={()=>setImportOpen(false)}>Cancelar</button><button className="primary" disabled={busy||!importRows.some(r=>r.valid)} onClick={confirmImport}>{busy?"Importando…":`Importar ${importRows.filter(r=>r.valid).length} produtos`}</button></div>
 </div></div>}
 {aiSettingsOpen&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setAiSettingsOpen(false)}}><div className="modal ai-settings-modal"><div className="modal-head"><h2>Conectar a OpenAI</h2><button onClick={()=>setAiSettingsOpen(false)}>×</button></div><div className="import-note"><strong>Configuração exclusiva do Master</strong><p>A chave será criptografada e não ficará visível para os demais usuários. O uso da API gera cobrança conforme os textos e imagens produzidos.</p></div><form onSubmit={saveAiSettings}><label>Chave da API da OpenAI<input name="apiKey" type="password" autoComplete="off" required placeholder="sk-…"/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setAiSettingsOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Conectando…":"Salvar e conectar"}</button></div></form></div></div>}
 {blingSettingsOpen&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setBlingSettingsOpen(false)}}><div className="modal ai-settings-modal"><div className="modal-head"><h2>Integração Bling</h2><button onClick={()=>setBlingSettingsOpen(false)}>×</button></div>{blingConnection?.connected?<><div className="connection-success"><strong>✓ Bling conectado</strong><p>A intranet já pode consultar produtos, depósitos, estoque e pedidos autorizados.</p></div><div className="modal-actions"><button className="secondary" onClick={()=>setBlingSettingsOpen(false)}>Fechar</button></div></>:isMaster?<><div className="import-note"><strong>Insira as credenciais somente aqui</strong><p>Copie o Client ID e revele o Client Secret no Bling. Ambos serão criptografados e o segredo não será exibido novamente.</p></div><form onSubmit={saveBlingSettings}><label>Client ID<input name="clientId" autoComplete="off" required defaultValue={blingConnection?.clientId||""} placeholder="Cole o Client ID do Bling"/></label><label>Client Secret<input name="clientSecret" type="password" autoComplete="new-password" required placeholder="Cole o Client Secret do Bling"/></label>{blingConnection?.lastError&&<div className="form-error">Bling: {blingConnection.lastError}</div>}{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setBlingSettingsOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Salvando…":"Salvar com segurança"}</button></div></form></>:<div className="form-error">A configuração inicial deve ser feita pelo usuário Master.</div>}</div></div>}
 {shopeeSettingsOpen&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget){setShopeeSettingsOpen(false);setShopeeReconfigure(false)}}}><div className="modal ai-settings-modal"><div className="modal-head"><h2>Integração Shopee</h2><button onClick={()=>{setShopeeSettingsOpen(false);setShopeeReconfigure(false)}}>×</button></div>{shopeeConnection?.connected&&!shopeeReconfigure?<><div className="connection-success"><strong>✓ Shopee {shopeeConnection.environment==="sandbox"?"Sandbox":"Produção"} conectada</strong><p>Loja {shopeeConnection.shopId}. A intranet já pode usar os recursos liberados neste ambiente.</p></div><div className="modal-actions"><button className="secondary" onClick={()=>setShopeeSettingsOpen(false)}>Fechar</button>{isMaster&&<button className="primary" onClick={()=>setShopeeReconfigure(true)}>{shopeeConnection.environment==="sandbox"?"Conectar conta real":"Trocar ambiente"}</button>}</div></>:isMaster?<><div className="import-note"><strong>{shopeeConnection?.environment==="sandbox"?"Conectar a conta real":"Configurar ambiente Shopee"}</strong><p>Selecione Produção e informe o Live Partner ID e a Live API Partner Key. As credenciais do Sandbox serão preservadas separadamente.</p></div><form onSubmit={saveShopeeSettings}><label>Ambiente<select name="environment" defaultValue={shopeeConnection?.environment==="sandbox"?"production":shopeeConnection?.environment||"sandbox"}><option value="sandbox">Sandbox — teste</option><option value="production">Produção — conta real</option></select></label><label>Partner ID do ambiente<input name="partnerId" inputMode="numeric" autoComplete="off" required placeholder="Somente números"/></label><label>API Partner Key do ambiente<input name="partnerKey" type="password" autoComplete="new-password" required placeholder="Cole a chave secreta da Shopee"/></label>{shopeeConnection?.lastError&&<div className="form-error">Shopee: {shopeeConnection.lastError}</div>}{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>{setShopeeSettingsOpen(false);setShopeeReconfigure(false)}}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Salvando…":"Salvar com segurança"}</button></div></form></>:<div className="form-error">A configuração inicial deve ser feita pelo usuário Master.</div>}</div></div>}
 {mlSettingsOpen&&<div className="modal-wrap" onMouseDown={e=>{if(e.target===e.currentTarget)setMlSettingsOpen(false)}}><div className="modal ai-settings-modal"><div className="modal-head"><h2>Integração Mercado Livre</h2><button onClick={()=>setMlSettingsOpen(false)}>×</button></div>{mlConnection?.connected?<><div className="connection-success"><strong>✓ Conta conectada</strong><p>Usuário Mercado Livre {mlConnection.mlUserId||"autorizado"}. A intranet já pode acessar os recursos permitidos.</p></div><div className="modal-actions"><button className="secondary" onClick={()=>setMlSettingsOpen(false)}>Fechar</button></div></>:isMaster?<><div className="import-note"><strong>Insira as credenciais somente aqui</strong><p>Use o App ID e o Client Secret renovado. Os dados serão criptografados e o segredo não será exibido novamente.</p></div><form onSubmit={saveMlSettings}><label>App ID<input name="clientId" inputMode="numeric" autoComplete="off" required defaultValue={mlConnection?.clientId||""} placeholder="Somente números"/></label><label>Client Secret renovado<input name="clientSecret" type="password" autoComplete="new-password" required placeholder="Cole a nova chave secreta"/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setMlSettingsOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Salvando…":"Salvar com segurança"}</button></div></form></>:<div className="form-error">A configuração inicial deve ser feita pelo usuário Master.</div>}</div></div>}
</div>
}
