import { cookies } from "next/headers";
import { getRuntimeDb } from "../db/runtime";

export const PERMISSIONS = ["painel","calendario","tarefas","materiais","preco_ecommerce","anuncios","cnpj","relatorios_cmv","produtos","compras","comercial","operacional","bancos","usuarios"] as const;
export type Permission = typeof PERMISSIONS[number];
export type AuthUser = { id:number; name:string; username:string; role:"master"|"user"; permissions:string[] };

export async function initAuth(){const db=getRuntimeDb();await db.prepare(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',permissions TEXT NOT NULL DEFAULT '[]',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();try{await db.prepare("ALTER TABLE users ADD COLUMN reset_requested_at TEXT").run()}catch{}await db.prepare(`CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run()}
const toHex=(b:Uint8Array)=>Array.from(b).map(x=>x.toString(16).padStart(2,"0")).join("");
const fromHex=(h:string)=>new Uint8Array((h.match(/.{1,2}/g)??[]).map(x=>parseInt(x,16)));
async function sha(value:string){return toHex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))))}
const PASSWORD_ITERATIONS=25000;
export async function hashPassword(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:PASSWORD_ITERATIONS,hash:"SHA-256"},key,256);return `v1:${PASSWORD_ITERATIONS}:${toHex(salt)}:${toHex(new Uint8Array(bits))}`}
export async function verifyPassword(password:string,stored:string){const parts=stored.split(":");const versioned=parts[0]==="v1";const iterations=versioned?Number(parts[1]):120000;const saltHash=versioned?parts[2]:parts[0];const expected=versioned?parts[3]:parts[1];if(!saltHash||!expected||!Number.isFinite(iterations))return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const actual=toHex(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:fromHex(saltHash),iterations,hash:"SHA-256"},key,256)));if(actual.length!==expected.length)return false;let diff=0;for(let i=0;i<actual.length;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0}
export async function createSession(userId:number){const raw=toHex(crypto.getRandomValues(new Uint8Array(32)));const expires=new Date(Date.now()+7*86400000);await getRuntimeDb().prepare("INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,?)").bind(userId,await sha(raw),expires.toISOString()).run();return {raw,expires}}
export async function destroySession(){const raw=(await cookies()).get("fg_session")?.value;if(raw)await getRuntimeDb().prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha(raw)).run()}
export async function currentUser():Promise<AuthUser|null>{await initAuth();const raw=(await cookies()).get("fg_session")?.value;if(!raw)return null;const row=await getRuntimeDb().prepare(`SELECT u.id,u.name,u.username,u.role,u.permissions FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.active=1`).bind(await sha(raw)).first<Record<string,unknown>>();if(!row)return null;const stored=JSON.parse(String(row.permissions||"[]")) as string[];return {id:Number(row.id),name:String(row.name),username:String(row.username),role:row.role==="master"?"master":"user",permissions:stored}}
export async function requirePermission(permission:Permission){const user=await currentUser();if(!user)throw new Response("Não autenticado",{status:401});if(user.role!=="master"&&!user.permissions.includes(permission))throw new Response("Sem permissão",{status:403});return user}
